# Generated by Django 2.2.7 on 2019-11-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20191121_0858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='RoomName',
        ),
        migrations.AlterModelTable(
            name='roomname',
            table='roomname',
        ),
    ]
