# Generated by Django 2.2.7 on 2019-11-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20191121_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomname',
            name='label',
        ),
    ]
