# Generated by Django 2.2.7 on 2019-11-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_roomname_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomname',
            options={'verbose_name_plural': 'Rooms'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='handle',
        ),
        migrations.AddField(
            model_name='roomname',
            name='username',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
