# Generated by Django 2.2.7 on 2019-11-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20191122_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomname',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='roomname',
            name='user2',
        ),
        migrations.AddField(
            model_name='roomname',
            name='username',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
