# Generated by Django 2.2.7 on 2019-11-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name_plural': 'Followers'},
        ),
        migrations.RenameField(
            model_name='followers',
            old_name='followers',
            new_name='followers_followers',
        ),
        migrations.RenameField(
            model_name='followers',
            old_name='following',
            new_name='followers_following',
        ),
    ]
